name: Deployment
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 12.x ]
        steps:
            -   uses: actions/checkout@v1
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Install Packages
                run: npm install
            -   name: Build page
                run: npm run build
                env:
                    REACT_APP_WEATHER_API_KEY: ${{ secrets.REACT_APP_WEATHER_API_KEY }}
            -   name: Deploy to gh-pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                    publish_dir: ./build
            -   name: executing remote ssh commands using ssh key
                uses: appleboy/ssh-action@master
                with:
                    host: react.goldenacker.de
                    username: ${{ secrets.GOLDENACKER_USER }}
                    password: ${{ secrets.GOLDENACKER_PASSWORD }}
                    port: 22
                    script: |
                        whoami
                        cd react.goldenacker.de
                        git pull origin gh-pages
                        ls -al
