name: DeploymentReactGoldenacker
on:
    push:
        branches:
            - gh-pages
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: executing remote ssh commands using ssh key
                uses: appleboy/ssh-action@master
                with:
                    host: react.goldenacker.de
                    username: ${{ secrets.GOLDENACKER_USER }}
                    password: ${{ secrets.GOLDENACKER_PASSWORD }}
                    port: 22
                    script: |
                        whoami
                        cd react.goldenacker.de
                        git pull
                        ls -al
